# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_gripper_control
    - right_gripper_control

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - LSP
      - LSR
      - LSY
      - LEB
      - LWY
      - LWP
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - RSP
      - RSR
      - RSY
      - REB
      - RWY
      - RWP
    action_ns: follow_joint_trajectory
    default: true
  left_gripper_control:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - LHAND_a1
      - LHAND_a2
      - LHAND_a3
      - LHAND_b1
      - LHAND_b2
      - LHAND_b3
      - LHAND_c1
      - LHAND_c2
      - LHAND_c3
    action_ns: follow_joint_trajectory
    default: true
  right_gripper_control:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - RHAND_a1
      - RHAND_a2
      - RHAND_a3
      - RHAND_b1
      - RHAND_b2
      - RHAND_b3
      - RHAND_c1
      - RHAND_c2
      - RHAND_c3
    action_ns: follow_joint_trajectory
    default: true